// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message

package su.postlink.protoc;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BodyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:postlink.Body)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 date = 1;</code>
     */
    boolean hasDate();
    /**
     * <code>required int64 date = 1;</code>
     */
    long getDate();

    /**
     * <code>required string body = 2;</code>
     */
    boolean hasBody();
    /**
     * <code>required string body = 2;</code>
     */
    java.lang.String getBody();
    /**
     * <code>required string body = 2;</code>
     */
    com.google.protobuf.ByteString
        getBodyBytes();

    /**
     * <code>required int32 idFrom = 3;</code>
     */
    boolean hasIdFrom();
    /**
     * <code>required int32 idFrom = 3;</code>
     */
    int getIdFrom();

    /**
     * <code>required string nickNameFrom = 4;</code>
     */
    boolean hasNickNameFrom();
    /**
     * <code>required string nickNameFrom = 4;</code>
     */
    java.lang.String getNickNameFrom();
    /**
     * <code>required string nickNameFrom = 4;</code>
     */
    com.google.protobuf.ByteString
        getNickNameFromBytes();

    /**
     * <code>required int32 idTo = 6;</code>
     */
    boolean hasIdTo();
    /**
     * <code>required int32 idTo = 6;</code>
     */
    int getIdTo();

    /**
     * <code>required string nickNameTo = 7;</code>
     */
    boolean hasNickNameTo();
    /**
     * <code>required string nickNameTo = 7;</code>
     */
    java.lang.String getNickNameTo();
    /**
     * <code>required string nickNameTo = 7;</code>
     */
    com.google.protobuf.ByteString
        getNickNameToBytes();
  }
  /**
   * Protobuf type {@code postlink.Body}
   */
  public  static final class Body extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:postlink.Body)
      BodyOrBuilder {
    // Use Body.newBuilder() to construct.
    private Body(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    public Body() {
      date_ = 0L;
      body_ = "";
      idFrom_ = 0;
      nickNameFrom_ = "";
      idTo_ = 0;
      nickNameTo_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Body(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              date_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              body_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              idFrom_ = input.readInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              nickNameFrom_ = bs;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000010;
              idTo_ = input.readInt32();
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              nickNameTo_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Message.internal_static_postlink_Body_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Message.internal_static_postlink_Body_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Message.Body.class, Message.Body.Builder.class);
    }

    private int bitField0_;
    public static final int DATE_FIELD_NUMBER = 1;
    private long date_;
    /**
     * <code>required int64 date = 1;</code>
     */
    public boolean hasDate() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 date = 1;</code>
     */
    public long getDate() {
      return date_;
    }

    public static final int BODY_FIELD_NUMBER = 2;
    private volatile java.lang.Object body_;
    /**
     * <code>required string body = 2;</code>
     */
    public boolean hasBody() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string body = 2;</code>
     */
    public java.lang.String getBody() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          body_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string body = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBodyBytes() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IDFROM_FIELD_NUMBER = 3;
    private int idFrom_;
    /**
     * <code>required int32 idFrom = 3;</code>
     */
    public boolean hasIdFrom() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 idFrom = 3;</code>
     */
    public int getIdFrom() {
      return idFrom_;
    }

    public static final int NICKNAMEFROM_FIELD_NUMBER = 4;
    private volatile java.lang.Object nickNameFrom_;
    /**
     * <code>required string nickNameFrom = 4;</code>
     */
    public boolean hasNickNameFrom() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string nickNameFrom = 4;</code>
     */
    public java.lang.String getNickNameFrom() {
      java.lang.Object ref = nickNameFrom_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nickNameFrom_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string nickNameFrom = 4;</code>
     */
    public com.google.protobuf.ByteString
        getNickNameFromBytes() {
      java.lang.Object ref = nickNameFrom_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nickNameFrom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IDTO_FIELD_NUMBER = 6;
    private int idTo_;
    /**
     * <code>required int32 idTo = 6;</code>
     */
    public boolean hasIdTo() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 idTo = 6;</code>
     */
    public int getIdTo() {
      return idTo_;
    }

    public static final int NICKNAMETO_FIELD_NUMBER = 7;
    private volatile java.lang.Object nickNameTo_;
    /**
     * <code>required string nickNameTo = 7;</code>
     */
    public boolean hasNickNameTo() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string nickNameTo = 7;</code>
     */
    public java.lang.String getNickNameTo() {
      java.lang.Object ref = nickNameTo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nickNameTo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string nickNameTo = 7;</code>
     */
    public com.google.protobuf.ByteString
        getNickNameToBytes() {
      java.lang.Object ref = nickNameTo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nickNameTo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBody()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIdFrom()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNickNameFrom()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIdTo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNickNameTo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, date_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, body_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, idFrom_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, nickNameFrom_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(6, idTo_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, nickNameTo_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, date_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, body_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, idFrom_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, nickNameFrom_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, idTo_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, nickNameTo_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Message.Body)) {
        return super.equals(obj);
      }
      Message.Body other = (Message.Body) obj;

      boolean result = true;
      result = result && (hasDate() == other.hasDate());
      if (hasDate()) {
        result = result && (getDate()
            == other.getDate());
      }
      result = result && (hasBody() == other.hasBody());
      if (hasBody()) {
        result = result && getBody()
            .equals(other.getBody());
      }
      result = result && (hasIdFrom() == other.hasIdFrom());
      if (hasIdFrom()) {
        result = result && (getIdFrom()
            == other.getIdFrom());
      }
      result = result && (hasNickNameFrom() == other.hasNickNameFrom());
      if (hasNickNameFrom()) {
        result = result && getNickNameFrom()
            .equals(other.getNickNameFrom());
      }
      result = result && (hasIdTo() == other.hasIdTo());
      if (hasIdTo()) {
        result = result && (getIdTo()
            == other.getIdTo());
      }
      result = result && (hasNickNameTo() == other.hasNickNameTo());
      if (hasNickNameTo()) {
        result = result && getNickNameTo()
            .equals(other.getNickNameTo());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasDate()) {
        hash = (37 * hash) + DATE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getDate());
      }
      if (hasBody()) {
        hash = (37 * hash) + BODY_FIELD_NUMBER;
        hash = (53 * hash) + getBody().hashCode();
      }
      if (hasIdFrom()) {
        hash = (37 * hash) + IDFROM_FIELD_NUMBER;
        hash = (53 * hash) + getIdFrom();
      }
      if (hasNickNameFrom()) {
        hash = (37 * hash) + NICKNAMEFROM_FIELD_NUMBER;
        hash = (53 * hash) + getNickNameFrom().hashCode();
      }
      if (hasIdTo()) {
        hash = (37 * hash) + IDTO_FIELD_NUMBER;
        hash = (53 * hash) + getIdTo();
      }
      if (hasNickNameTo()) {
        hash = (37 * hash) + NICKNAMETO_FIELD_NUMBER;
        hash = (53 * hash) + getNickNameTo().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Message.Body parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message.Body parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message.Body parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message.Body parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message.Body parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Message.Body parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Message.Body parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Message.Body parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Message.Body parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Message.Body parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Message.Body prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code postlink.Body}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:postlink.Body)
        Message.BodyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Message.internal_static_postlink_Body_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Message.internal_static_postlink_Body_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Message.Body.class, Message.Body.Builder.class);
      }

      // Construct using su.postlink.protoc.Message.Body.newBuilder()
      public Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        date_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        body_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        idFrom_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        nickNameFrom_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        idTo_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        nickNameTo_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Message.internal_static_postlink_Body_descriptor;
      }

      public Message.Body getDefaultInstanceForType() {
        return Message.Body.getDefaultInstance();
      }

      public Message.Body build() {
        Message.Body result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Message.Body buildPartial() {
        Message.Body result = new Message.Body(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.date_ = date_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.body_ = body_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.idFrom_ = idFrom_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.nickNameFrom_ = nickNameFrom_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.idTo_ = idTo_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.nickNameTo_ = nickNameTo_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Message.Body) {
          return mergeFrom((Message.Body)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Message.Body other) {
        if (other == Message.Body.getDefaultInstance()) return this;
        if (other.hasDate()) {
          setDate(other.getDate());
        }
        if (other.hasBody()) {
          bitField0_ |= 0x00000002;
          body_ = other.body_;
          onChanged();
        }
        if (other.hasIdFrom()) {
          setIdFrom(other.getIdFrom());
        }
        if (other.hasNickNameFrom()) {
          bitField0_ |= 0x00000008;
          nickNameFrom_ = other.nickNameFrom_;
          onChanged();
        }
        if (other.hasIdTo()) {
          setIdTo(other.getIdTo());
        }
        if (other.hasNickNameTo()) {
          bitField0_ |= 0x00000020;
          nickNameTo_ = other.nickNameTo_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDate()) {
          return false;
        }
        if (!hasBody()) {
          return false;
        }
        if (!hasIdFrom()) {
          return false;
        }
        if (!hasNickNameFrom()) {
          return false;
        }
        if (!hasIdTo()) {
          return false;
        }
        if (!hasNickNameTo()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Message.Body parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Message.Body) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long date_ ;
      /**
       * <code>required int64 date = 1;</code>
       */
      public boolean hasDate() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 date = 1;</code>
       */
      public long getDate() {
        return date_;
      }
      /**
       * <code>required int64 date = 1;</code>
       */
      public Builder setDate(long value) {
        bitField0_ |= 0x00000001;
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 date = 1;</code>
       */
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000001);
        date_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object body_ = "";
      /**
       * <code>required string body = 2;</code>
       */
      public boolean hasBody() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string body = 2;</code>
       */
      public java.lang.String getBody() {
        java.lang.Object ref = body_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            body_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string body = 2;</code>
       */
      public com.google.protobuf.ByteString
          getBodyBytes() {
        java.lang.Object ref = body_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          body_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string body = 2;</code>
       */
      public Builder setBody(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string body = 2;</code>
       */
      public Builder clearBody() {
        bitField0_ = (bitField0_ & ~0x00000002);
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      /**
       * <code>required string body = 2;</code>
       */
      public Builder setBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        body_ = value;
        onChanged();
        return this;
      }

      private int idFrom_ ;
      /**
       * <code>required int32 idFrom = 3;</code>
       */
      public boolean hasIdFrom() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 idFrom = 3;</code>
       */
      public int getIdFrom() {
        return idFrom_;
      }
      /**
       * <code>required int32 idFrom = 3;</code>
       */
      public Builder setIdFrom(int value) {
        bitField0_ |= 0x00000004;
        idFrom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 idFrom = 3;</code>
       */
      public Builder clearIdFrom() {
        bitField0_ = (bitField0_ & ~0x00000004);
        idFrom_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object nickNameFrom_ = "";
      /**
       * <code>required string nickNameFrom = 4;</code>
       */
      public boolean hasNickNameFrom() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string nickNameFrom = 4;</code>
       */
      public java.lang.String getNickNameFrom() {
        java.lang.Object ref = nickNameFrom_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            nickNameFrom_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string nickNameFrom = 4;</code>
       */
      public com.google.protobuf.ByteString
          getNickNameFromBytes() {
        java.lang.Object ref = nickNameFrom_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nickNameFrom_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string nickNameFrom = 4;</code>
       */
      public Builder setNickNameFrom(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        nickNameFrom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string nickNameFrom = 4;</code>
       */
      public Builder clearNickNameFrom() {
        bitField0_ = (bitField0_ & ~0x00000008);
        nickNameFrom_ = getDefaultInstance().getNickNameFrom();
        onChanged();
        return this;
      }
      /**
       * <code>required string nickNameFrom = 4;</code>
       */
      public Builder setNickNameFromBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        nickNameFrom_ = value;
        onChanged();
        return this;
      }

      private int idTo_ ;
      /**
       * <code>required int32 idTo = 6;</code>
       */
      public boolean hasIdTo() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 idTo = 6;</code>
       */
      public int getIdTo() {
        return idTo_;
      }
      /**
       * <code>required int32 idTo = 6;</code>
       */
      public Builder setIdTo(int value) {
        bitField0_ |= 0x00000010;
        idTo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 idTo = 6;</code>
       */
      public Builder clearIdTo() {
        bitField0_ = (bitField0_ & ~0x00000010);
        idTo_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object nickNameTo_ = "";
      /**
       * <code>required string nickNameTo = 7;</code>
       */
      public boolean hasNickNameTo() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string nickNameTo = 7;</code>
       */
      public java.lang.String getNickNameTo() {
        java.lang.Object ref = nickNameTo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            nickNameTo_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string nickNameTo = 7;</code>
       */
      public com.google.protobuf.ByteString
          getNickNameToBytes() {
        java.lang.Object ref = nickNameTo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nickNameTo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string nickNameTo = 7;</code>
       */
      public Builder setNickNameTo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        nickNameTo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string nickNameTo = 7;</code>
       */
      public Builder clearNickNameTo() {
        bitField0_ = (bitField0_ & ~0x00000020);
        nickNameTo_ = getDefaultInstance().getNickNameTo();
        onChanged();
        return this;
      }
      /**
       * <code>required string nickNameTo = 7;</code>
       */
      public Builder setNickNameToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        nickNameTo_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:postlink.Body)
    }

    // @@protoc_insertion_point(class_scope:postlink.Body)
    private static final Message.Body DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Message.Body();
    }

    public static Message.Body getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Body>
        PARSER = new com.google.protobuf.AbstractParser<Body>() {
      public Body parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Body(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Body> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Body> getParserForType() {
      return PARSER;
    }

    public Message.Body getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_postlink_Body_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_postlink_Body_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\007message\022\010postlink\"j\n\004Body\022\014\n\004date\030\001 \002(" +
      "\003\022\014\n\004body\030\002 \002(\t\022\016\n\006idFrom\030\003 \002(\005\022\024\n\014nickN" +
      "ameFrom\030\004 \002(\t\022\014\n\004idTo\030\006 \002(\005\022\022\n\nnickNameT" +
      "o\030\007 \002(\tB\026\n\013su.postlinkB\007Message"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_postlink_Body_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_postlink_Body_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_postlink_Body_descriptor,
        new java.lang.String[] { "Date", "Body", "IdFrom", "NickNameFrom", "IdTo", "NickNameTo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
